# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 390)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.searchBox = QtWidgets.QLineEdit(parent=Dialog)
        self.searchBox.setGeometry(QtCore.QRect(0, 0, 411, 20))
        self.searchBox.setToolTip("")
        self.searchBox.setText("")
        self.searchBox.setObjectName("searchBox")
        self.productsList = QtWidgets.QListWidget(parent=Dialog)
        self.productsList.setGeometry(QtCore.QRect(0, 20, 411, 301))
        self.productsList.setObjectName("productsList")
        self.activateButton = QtWidgets.QPushButton(parent=Dialog)
        self.activateButton.setEnabled(False)
        self.activateButton.setGeometry(QtCore.QRect(-10, 320, 421, 71))
        self.activateButton.setObjectName("activateButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "POKMS"))
        self.searchBox.setPlaceholderText(_translate("Dialog", "Поиск"))
        self.activateButton.setText(_translate("Dialog", "Активировать"))
